user default off nopass -@all
user cassiopeia on >CASSIOPEIA_PASSWORD_PLACEHOLDER ~* &* +@all
user community on >COMMUNITY_PASSWORD_PLACEHOLDER ~cassiopeia:results:* ~cassiopeia:dlq resetchannels +rpush +llen
